[package]
name = "cyclonedds-rs"
version = "0.6.4"
description = "Safe Rust bindings for cyclonedds"
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
cdr = "0.2.4"
cyclonedds-sys.workspace = true
murmur3 = "0.5.2"
serde = "1.0.228"
serde_derive = "1.0.228"
thiserror = "2.0.18"

[features]
shm = ["cyclonedds-sys/shm"]
default = ["shm"]

[dev-dependencies]
cyclonedds-derive.workspace = true
tokio = { version = "1.50.0", features = ["full"] }
