[package]
name = "cyclonedds-rs"
version = "0.6.4"
description = "Safe Rust bindings for cyclonedds"
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
cdr = "0.2.4"
cyclonedds-sys.workspace = true
futures-util = "0.3.32"
murmur3 = "0.5.2"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tracing = "0.1.44"
uuid = "1.21.0"

[features]
shm = ["cyclonedds-sys/shm"]
default = ["shm"]

[dev-dependencies]
anyhow = "1.0.102"
cyclonedds-derive.workspace = true
test-log = { version = "0.2.19", default-features = false, features = ["trace"] }
tokio = { version = "1.50.0", features = ["full"] }
tokio-util = "0.7.16"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
