name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: | 
        sudo apt-get install libacl1-dev
        git clone https://github.com/eclipse-iceoryx/iceoryx.git
        cd iceoryx
        git checkout release_2.0
        pushd .
        mkdir build
        cd build
        cmake ../iceoryx_meta/
        sudo make install
        popd
        git clone https://github.com/eclipse-cyclonedds/cyclonedds.git
        cd cyclonedds
        git checkout releases/0.10.x
        mkdir build
        cd build
        cmake ..
        sudo make install
        cargo build --verbose
    - name: Run tests
      run: | 
        export LD_LIBRARY_PATH=/usr/local/lib
        cargo test --verbose
